FROM heroku/heroku:18

COPY . /app
WORKDIR /app

# Setup buildpack
RUN mkdir -p /tmp/buildpack/heroku/go /tmp/build_cache /tmp/env
RUN curl -s https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/go.tgz | tar xvz -C /tmp/buildpack/heroku/go

#Execute Buildpack
RUN STACK=heroku-18 /tmp/buildpack/heroku/go/bin/compile /app /tmp/build_cache /tmp/env

ENV HOME /app
WORKDIR /app
RUN useradd -m heroku
USER heroku
CMD echo Go! Gopher!
